const EErros = {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    INVALID_VALUE_ERROR: 3,
    INVALID_LENGTH_ERROR: 4,
    INVALID_FORMAT_ERROR: 5,
    INVALID_RANGE_ERROR: 6,
    PRODUCT_NOT_FOUND: 7,
    PRODUCT_ALREADY_EXISTS: 8,
    PRODUCT_NOT_AVAILABLE: 9,
    PRODUCT_NOT_IN_CART: 10,
    CART_NOT_FOUND: 11,
    CART_ALREADY_EXISTS: 12,
    CART_NOT_AVAILABLE: 13,
}

export default EErros